# Grade 1 Science Questions and Answers
N1 = ["What is the Earth's primary source of light?", "Moon", "Sun", "Stars", "Lightning", 2]
N2 = ["Name three different animals that can fly.", "Dog, Cow, Horse", "Fish, Whale, Dolphin", "Sparrow, Eagle, Butterfly", "Lion, Tiger, Leopard", 3]
N3 = ["What do plants need to grow?", "Water, Soil, Air", "Rocks, Sand, Cement", "Oil, Gasoline, Fuel", "Iron, Copper, Aluminum", 1]
N4 = ["What is the name of the closest star to Earth?", "Mars", "Jupiter", "Sun", "Moon", 3]
N5 = ["What is the process by which plants make their own food?", "Photosynthesis", "Respiration", "Digestion", "Fermentation", 1]
N6 = ["What causes thunder during a storm?", "Lightning", "Rain", "Wind", "Clouds", 4]
N7 = ["What do we call the process of water turning into ice?", "Condensation", "Melting", "Freezing", "Evaporation", 3]
N8 = ["Name two animals that live in water.", "Elephant, Giraffe", "Zebra, Karemovedroo", "Penguin, Dolphin", "Lion, Tiger", 3]
N9 = ["How do we measure temperature?", "Barometer", "Thermometer", "Ruler", "Compass", 2]
N10 = ["What are the different seasons of the year?",  "Spring, Summer, Fall, Winter",  "Morning, Afternoon, Evening",  "Rainy, Cloudy, Sunny",  "Hot, Warm, Cold",  1]

# Grade 2 Science Questions and Answers
N11 = ["What are the three states of matter?", "Solid, Gas, Vapor", "Liquid, Vapor, Gas", "Solid, Liquid, Gas", "Ice, Water, Steam", 3]
N12 = ["Name the planets in our solar system.", "Mars, Venus, Earth", "Jupiter, Saturn, Pluto", "Mercury, Venus, Mars", "Earth, Moon, Sun", 3]
N13 = ["How do plants make oxygen?", "Respiration", "Photosynthesis", "Decomposition", "Transpiration", 2]
N14 = ["What causes day and night on Earth?", "Rotation", "Revolution", "Refraction", "Reflection", 1]
N15 = ["What do we call the force that pulls objects toward the center of the Earth?", "Push", "Pull", "Gravity", "Magnetism", 3]
N16 = ["How do shadows form?", "Absorption", "Reflection", "Refraction", "Blocking of light", 4]
N17 = ["What is the role of the heart in the human body?", "Circulation", "Digestion", "Respiration", "Excretion", 1]
N18 = ["Name three different sources of energy.", "Oil, Gasoline, Coal", "Sun, Wind, Water", "Fire, Lightning, Electricity", "Metal, Wood, Plastic", 2]
N19 = ["What is the difference between weather and climate?", "Same thing", "Weather is short-term, Climate is long-term", "Climate is short-term, Weather is long-term", "Weather is hot, Climate is cold", 2]
N200 = ["How do animals adapt to their environment?",  "By moving to another place",  "By changing their body shape",  "By learning new skills",  "By evolving over time",  1]

# Grade 3 Science Questions and Answers
N21 = ["What is photosynthesis?", "Process of breathing", "Process of making food", "Process of burning", "Process of sleeping", 2]
N22 = ["Name the five senses.", "Sight, Taste, Smell, Touch, Hearing", "Vision, Taste, Smell, Movement, Speech", "Eyesight, Taste, Feeling, Hearing, Thinking", "Seeing, Hearing, Tasting, Smelling, Touching", 1]
N23 = ["What is the difference between a herbivore and a carnivore?", "Herbivores eat only meat, carnivores eat only plants", "Herbivores eat only plants, carnivores eat only meat", "Herbivores eat both plants and meat, carnivores eat only plants", "Herbivores eat only meat, carnivores eat both plants and meat", 2]
N24 = ["How do plants reproduce?", "By laying eggs", "By giving birth to live young", "By seeds and spores", "By pollinating flowers", 3]
N25 = ["What is the function of the nervous system?", "Control body movements", "Transport oxygen", "Pump blood", "Digest food", 1]
N26 = ["What is a food chain?", "A chain made of food", "A chain that holds animals", "A sequence of who eats whom in an ecosystem", "A chain used for cooking food", 3]
N27 = ["Name three renewable sources of energy.", "Coal, Oil, Natural Gas", "Wind, Solar, Hydroelectric", "Nuclear, Biomass, Geothermal", "Wood, Fossil Fuels, Uranium", 2]
N28 = ["How does a volcano erupt?", "With water", "With snow", "With lava, ash, and gases", "With rocks", 3]
N29 = ["Explain the water cycle.", "The cycle of water turning into ice", "The cycle of water moving from oceans to clouds to rain and back again", "The cycle of water evaporating into space", "The cycle of water flowing in rivers only", 2]
N30 = ["What is the role of the nucleus in a cell?",  "Controls cell activities",  "Makes energy for the cell",  "Helps the cell move",  "Provides support to the cell",  1]

# Grade 4 Science Questions and Answers
N31 = ["What is the difference between a solid, liquid, and gas?", "Shape and volume", "Shape only", "Volume only", "Neither shape nor volume", 1]
N32 = ["Name the four layers of the Earth.", "Crust, Mantle, Outer core, Inner core", "Atmosphere, Lithosphere, Hydrosphere, Biosphere", "Soil, Water, Air, Rock", "Troposphere, Stratosphere, Mesosphere, Thermosphere", 1]
N33 = ["How does sound travel?", "Through vacuum", "Through solid, liquid, or gas", "Through light", "Through fire", 2]
N34 = ["What causes tides in the ocean?", "Earth's rotation", "Moon's gravity", "Sun's gravity", "Wind", 2]
N35 = ["What is the function of the digestive system?", "Pump blood", "Control body movements", "Break down food", "Transport oxygen", 3]
N36 = ["Explain the process of evaporation.", "Water turning into ice", "Water turning into vapor", "Water boiling", "Water freezing", 2]
N37 = ["What is a simple machine?", "A machine that works with electricity", "A machine that uses multiple steps", "A machine with few or no moving parts", "A machine that is difficult to use", 3]
N38 = ["How do plants and animals depend on each other?", "Plants give animals oxygen, and animals give plants carbon dioxide", "Plants provide food and oxygen for animals, and animals provide carbon dioxide and nutrients for plants", "Plants provide shade for animals, and animals provide protection for plants", "Plants and animals do not depend on each other", 2]
N39 = ["What is the role of chlorophyll in photosynthesis?", "Absorbs light energy", "Releases oxygen", "Breaks down food", "Produces water", 1]
N40 = ["Explain the concept of buoyancy.",  "The upward force that keeps things afloat",  "The downward force of gravity",  "The force of friction between objects",  "The force of air resistance on objects",  1]

# Grade 5 Science Questions and Answers
N41 = ["What is the largest planet in our solar system?", "Earth", "Mars", "Jupiter", "Saturn", 3]
N42 = ["How do plants make their own food?", "By eating other plants", "By capturing and eating insects", "By a process called photosynthesis", "By absorbing nutrients from the soil", 3]
N43 = ["What is the Earth's primary source of energy?", "Wind", "Water", "Sun", "Geothermal heat", 3]
N44 = ["What is the process by which water changes from a liquid to a gas?", "Condensation", "Evaporation", "Precipitation", "Sublimation", 2]
N45 = ["Which of the following is a renewable resource?", "Natural Gas", "Coal", "Solar Energy", "Nuclear Energy", 3]
N46 = ["What is the main function of the cell membrane?", "To regulate the passage of substances into and out of the cell", "To provide structural support to the cell", "To store genetic material", "To produce energy for the cell", 1]
N47 = ["How do we classify animals with a backbone?", "Invertebrates", "Fish", "Reptiles", "Vertebrates", 4]
N48 = ["What is the force that pulls objects towards the center of the Earth?", "Magnetism", "Gravity", "Friction", "Buoyancy", 2]
N49 = ["What is the process by which plants make their own food using sunlight?", "Transpiration", "Respiration", "Fermentation", "Photosynthesis", 4]
N50 = ["Which planet is known as the 'Red Planet'?",  "Venus",  "Jupiter",  "Mars",  "Saturn",  3]

# Grade 6 Science Questions and Answers
N51 = ["What is the powerhouse of the cell?", "Nucleus", "Mitochondria", "Ribosomes", "Endoplasmic Reticulum", 2]
N52 = ["What is the process by which plants make their own food?", "Cellular Respiration", "Transpiration", "Photosynthesis", "Fermentation", 3]
N53 = ["Which of the following is a conductor of electricity?", "Rubber", "Plastic", "Copper", "Wood", 3]
N54 = ["What is the Earth's outermost layer called?", "Crust", "Mantle", "Core", "Lithosphere", 1]
N55 = ["What is the role of the ozone layer in the atmosphere?", "To trap carbon dioxide", "To protect against ultraviolet (UV) radiation", "To produce oxygen", "To regulate temperature", 2]
N56 = ["How does sound travel through a medium?", "Through electromagnetic waves", "Through convection", "Through compression and rarefaction of molecules", "Through nuclear reactions", 3]
N57 = ["Which of the following is a renewable energy source?", "Natural Gas", "Coal", "Solar Power", "Nuclear Power", 3]
N58 = ["What is the process of a gas changing into a liquid?", "Evaporation", "Condensation", "Sublimation", "Boiling", 2]
N59 = ["What is the function of the nucleus in a cell?", "To produce energy", "To control cell activities and store genetic information", "To synthesize proteins", "To provide structural support", 2]
N60 = ["Which planet is known as the 'Blue Planet'?",  "Earth",  "Neptune",  "Uranus",  "Mercury",  1]

# Grade 7 Science Questions and Answers
N61 = ["What is the process by which plants make their own food using sunlight?", "Respiration", "Photosynthesis", "Fermentation", "Transpiration", 2]
N62 = ["What is the basic unit of life?", "Cell", "Molecule", "Organism", "Tissue", 1]
N63 = ["What is the Earth's primary source of energy?", "Wind", "Water", "Sun", "Geothermal heat", 3]
N64 = ["What is the function of the respiratory system?", "To transport oxygen to cells", "To produce hormones", "To fight off diseases and infections", "To digest food", 1]
N65 = ["How do plants obtain the nutrients they need for growth?", "By breathing in carbon dioxide", "By absorbing nutrients through their roots", "By capturing and eating insects", "By drinking water", 2]
N66 = ["What is the force that opposes motion between two surfaces in contact?", "Gravity", "Friction", "Magnetism", "Buoyancy", 2]
N67 = ["What is the role of the nucleus in a cell?", "To produce energy", "To control cell activities and store genetic information", "To synthesize proteins", "To provide structural support", 2]
N68 = ["Which of the following is a renewable resource?", "Natural Gas", "Coal", "Solar Energy", "Nuclear Energy", 3]
N69 = ["What is the function of the nervous system?", "To transport oxygen to cells", "To produce hormones", "To regulate body temperature", "To transmit signals between body parts", 4]
N70 = ["What is the process by which rocks are broken down into smaller particles?",  "Erosion",  "Deposition",  "Weathering",  "Sedimentation",  3]
# Grade 8 Science Questions and Answers
N71 = ["What is the main function of the cell membrane?", "To regulate the passage of substances into and out of the cell", "To provide structural support to the cell", "To store genetic material", "To produce energy for the cell", 1]
N72 = ["Explain the differences between an element and a compound.", "An element is a pure substance made up of only one type of atom; a compound is a substance made up of two or more different types of atoms", "An element is a combination of atoms; a compound is a single type of atom", "An element is a mixture; a compound is a pure substance", "An element is a gas; a compound is a solid", 1]
N73 = ["What are the laws of motion?", "Law of Inertia, Law of Relativity, Law of Thermodynamics", "Law of Conservation of Mass, Law of Conservation of Energy, Law of Conservation of Momentum", "Law of Motion, Law of Force, Law of Gravity", "A"]
N74 = ["Explain the difference between a series circuit and a parallel circuit.", "In a series circuit, components are connected in parallel; in a parallel circuit, components are connected in series", "In a series circuit, components are connected end-to-end; in a parallel circuit, components are connected side-by-side", "In a series circuit, current has only one path to flow; in a parallel circuit, current has multiple paths to flow", "In a series circuit, voltage is constant across all components; in a parallel circuit, voltage varies across components", 3]
N75 = ["What is the role of the ozone layer in protecting the Earth?", "It absorbs ultraviolet radiation from the Sun", "It absorbs infrared radiation from the Sun", "It absorbs visible light from the Sun", "It reflects radio waves from the Sun", 1]
N76 = ["How do we classify stars?", "Based on their size and color", "Based on their distance from Earth", "Based on their composition", "Based on their brightness", 1]
N77 = ["Explain the difference between potential and kinetic energy.", "Potential energy is stored energy, kinetic energy is energy in motion", "Potential energy is the energy of position, kinetic energy is the energy of motion", "Potential energy increases with velocity, kinetic energy decreases with velocity", "Potential energy is constant, kinetic energy varies with mass", 1]
N78 = ["What is the function of the lymphatic system?", "To transport oxygen to cells", "To produce hormones", "To fight off diseases and infections", "To digest food", 3]
N79 = ["How do we calculate density?", "Density = Mass / Volume", "Density = Volume / Mass", "Density = Mass x Volume", "Density = Mass + Volume", 1]
N80 = ["What is the difference between heat and temperature?",  "Heat is the transfer of thermal energy, temperature is the measure of thermal energy",  "Heat is the measure of thermal energy, temperature is the transfer of thermal energy",  "Heat is always positive, temperature can be negative",  "Heat is measured in degrees Celsius, temperature is measured in joules",  1]

# Grade 9 Science Questions and Answers
N81 = ["What is the difference between a prokaryotic cell and a eukaryotic cell?", "Prokaryotic cells have a nucleus, eukaryotic cells do not", "Prokaryotic cells are smaller than eukaryotic cells", "Prokaryotic cells have membrane-bound organelles, eukaryotic cells do not", "Prokaryotic cells have DNA, eukaryotic cells do not", 1]
N82 = ["Explain the difference between DNA and RNA.", "DNA contains thymine, RNA contains uracil", "DNA is single-stranded, RNA is double-stranded", "DNA carries genetic information, RNA carries oxygen", "DNA is found only in eukaryotic cells, RNA is found only in prokaryotic cells", 1]
N83 = ["How do we classify different types of chemical reactions?", "Based on their energy content", "Based on the speed of reaction", "Based on the reactants and products involved", "Based on the temperature required", 3]
N84 = ["What is the difference between an exothermic and endothermic reaction?", "Exothermic reactions release energy, endothermic reactions absorb energy", "Exothermic reactions absorb energy, endothermic reactions release energy", "Exothermic reactions occur at high temperatures, endothermic reactions occur at low temperatures", "Exothermic reactions occur spontaneously, endothermic reactions require a catalyst", 1]
N85 = ["Explain the process of natural selection.", "The process by which organisms adapt to their environment", "The process by which individuals with favorable traits survive and reproduce", "The process by which species become extinct", "The process by which organisms migrate to new habitats", 2]
N86 = ["How do we measure the concentration of a solution?", "With a barometer", "With a thermometer", "With a hydrometer", "With a spectrophotometer or titration", 4]
N87 = ["What is the difference between speed and velocity?", "Speed is a scalar quantity, velocity is a vector quantity", "Speed is measured in meters per second, velocity is measured in kilometers per hour", "Speed is the rate of change of position, velocity is the rate of change of displacement", "Speed is constant, velocity is variable", 1]
N88 = ["Explain the difference between potential and kinetic energy.", "Potential energy is stored energy, kinetic energy is energy in motion", "Potential energy is energy in motion, kinetic energy is stored energy", "Potential energy is always positive, kinetic energy is always negative", "Potential energy is measured in joules, kinetic energy is measured in meters per second", 1]
N89 = ["What is the difference between renewable and non-renewable resources?", "Renewable resources can be replaced, non-renewable resources cannot", "Non-renewable resources can be replaced, renewable resources cannot", "Renewable resources are found underground, non-renewable resources are found above ground", "Renewable resources are only used in industry, non-renewable resources are used by individuals", 1]
N90 = ["How do we calculate work and power?",  "Work = Force x Distance, Power = Work / Time",  "Work = Mass x Acceleration, Power = Force x Distance",  "Work = Energy / Time, Power = Force x Distance",  "Work = Pressure x Volume, Power = Energy / Time",  1]

# Grade 10 Science Questions and Answers
N91 = ["Explain the structure of an atom.",  "Atoms consist of a nucleus (protons and neutrons) surrounded by electrons",  "Atoms consist of a single particle called a nucleon",  "Atoms consist of only electrons",  "Atoms consist of protons and electrons, with no nucleus",  1]
N92 = ["What is the difference between an element and a compound?",  "An element is a pure substance made of only one type of atom; a compound is a substance made of two or more different types of atoms",  "An element is a combination of atoms; a compound is a single type of atom",  "An element is a mixture; a compound is a pure substance",  "An element is a gas; a compound is a solid",  1]
N93 = ["How does the process of cellular respiration differ from photosynthesis?",  "Cellular respiration releases energy from food; photosynthesis uses energy to produce food",  "Cellular respiration and photosynthesis are the same process",  "Cellular respiration produces oxygen; photosynthesis consumes oxygen",  "Cellular respiration uses sunlight; photosynthesis releases energy",  1]
N94 = ["Explain the difference between a physical change and a chemical change.",  "Physical change alters the state of matter; chemical change alters the composition",  "Physical change involves heat; chemical change involves light",  "Physical change involves evaporation; chemical change involves condensation",  "Physical change involves a change in color; chemical change involves a change in shape",  1]
N95 = ["What is the role of DNA in genetics?",  "DNA carries genetic information and instructions for the development and functioning of living organisms",  "DNA is responsible for producing energy in cells",  "DNA is involved only in bacterial genetics",  "DNA is found only in plant cells",  1]
N96 = ["Explain the laws of reflection and refraction of light.",  "The law of reflection states that the angle of incidence is equal to the angle of reflection; the law of refraction states that the angle of incidence is equal to the angle of refraction",  "The law of reflection states that light bends as it passes through different media; the law of refraction states that light reflects off surfaces",  "The law of reflection states that light travels in a straight line; the law of refraction states that light has a curved path",  "The law of reflection states that light slows down in denser media; the law of refraction states that light speeds up in denser media",  1]
N97 = ["How do we classify organisms into different domains and kingdoms?",  "Based on their habitat",  "Based on their genetic similarities",  "Based on their size",  "Based on their age",  2]
N98 = ["Explain the differences between meiosis and mitosis.",  "Meiosis produces cells with half the number of chromosomes; mitosis produces cells with the same number of chromosomes",  "Meiosis produces identical daughter cells; mitosis produces genetically unique cells",  "Meiosis occurs only in plants; mitosis occurs only in animals",  "Meiosis is a process of growth; mitosis is a process of reproduction",  1]
N99 = ["What is the function of the endocrine system in the human body?",  "To produce hormones that regulate various body functions",  "To pump blood throughout the body",  "To digest food and absorb nutrients",  "To transport oxygen to cells",  1]
N100 = ["Explain the difference between an exothermic and endothermic reaction.",   "Exothermic reactions release energy; endothermic reactions absorb energy",   "Exothermic reactions absorb energy; endothermic reactions release energy",   "Exothermic reactions only occur in living organisms; endothermic reactions only occur in non-living substances",   "Exothermic reactions require a catalyst; endothermic reactions occur spontaneously",   1]